INSERT INTO category (title) VALUES ('Computer Science');
INSERT INTO category (title) VALUES ('Design');

INSERT INTO course (title, description, price, category_id, number_of_purchases, image_url) VALUES ('Node.js with Anders', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 8000, 1, 1, 'https://www.teq.com/blog/wp-content/uploads/2016/02/iStock_000078050265_Medium.jpg');
INSERT INTO course (title, description, price, category_id, number_of_purchases, image_url) VALUES ('Machine Learning with Jon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 7500, 1, 1, 'https://g.foolcdn.com/editorial/images/464092/frustrated-man-looking-at-computer-anxious-nervous-confused.jpg');
INSERT INTO course (title, description, price, category_id, number_of_purchases, image_url) VALUES ('React with Christian', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 7750, 1, 1, 'https://www.carltontrailcollege.com/explore/computer-and-technology-training/computer-and-technology-training-1-.jpg');
INSERT INTO course (title, description, price, category_id, image_url) VALUES ('HTML/CSS with Bob John', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 12000, 1, 'https://rapidpurple.com/v2/wp-content/uploads/2013/08/pace-oregon-state-html-css-coding-web-design.jpg');
-- INSERT INTO course (title, description, price, category_id) VALUES ('JavaScript with Bubber', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 23000, 1);
-- INSERT INTO course (title, description, price, category_id) VALUES ('Jewelery Crafts with Angelina', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 4000, 2);
-- INSERT INTO course (title, description, price, category_id) VALUES ('Furniture Design with Nicolai', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.', 16000, 2);
